# Generated by Django 2.2.1 on 2019-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='promo',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='signature',
            field=models.CharField(default='FILLER', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='FILLER', max_length=64),
        ),
    ]
