# Generated by Django 2.2.1 on 2019-06-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_assos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
